---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность добавлять товары в корзину и продолжать покупки дальше
  - На странице товара и в каталоге выводится название, рейтинг, цена со скидкой и без нее
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - В зависимости от языка меять описание у товаров
  - Нужны пояснения ко всем цифрам в карточкахтовара
  - Лого магазина должно перенаправлять на домашнюю страницу
  - В выборе категорий должна быть категория Все (All), которая возвращает отображение всех товаров
  - Должны быть контакты магазина и способы связи
  - Должна присутствовать форма, в которой покупатель оставляет свои данные для связи
  - Пользователь должен иметь возможность менять количество покупаемых товаров в корзине
  - Из карточки товара должна быть возможность вернуться обратно в магазин

  




